from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.skelett_history_classifier.skelett_history_classifier import SkelettHistoryClassifier